server:
  port: 8091
spring:
  application:
    name: scaffold
  datasource:
    url: jdbc:mysql://localhost:3307/scaffold?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    username: root
    password: tianjingle
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      stat-view-servlet:
        allow: true
  pengzu:
   sms:
     sms-type: tentcent
     security-key: 414c40f8dcd85a9806db3be68ecde570
     appid: 1400218666
     sign: 100010506137

mybatis:
  type-aliases-package: com.inclination.scaffold.infrastraction.repository.po
  mapper-locations: classpath:mapper/*.xml

logging:
  config: classpath:config/log4j2-dev.xml
  
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

app:
  id: scaffold
apollo:
  meta: http://127.0.0.1:8080
  bootstrap:
    enabled: true
    eagerLoad:
      enabled: true
    namespaces: application,TEST1.common

#liquibase:
#  change-log: classpath:db/changelog-master.xml
#  user: root
#  password: tianjingle
#  url: jdbc:mysql://localhost:3307/scaffold?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
#  enabled: true
#  drop-first: false