server:
  port: 8091
  servlet:
    context-path: /scaffold

logging:
  config: classpath:config/log4j2-dev.xml
spring:
  application:
    name: scaffold
  datasource:
    url: jdbc:mysql://localhost:3307/scaffold?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    username: root
    password: tianjingle
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      stat-view-servlet:
        allow: true
  pengzu:
   sms:
     sms-type: tentcent
     security-key: 414c40f8dcd85a9806db3be68ecde570
     appid: 1400218666
     sign: 100010506137
  liquibase:
    drop-first: false
    enabled: true
    url: jdbc:mysql://localhost:3307/scaffold?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    password: tianjingle
    user: root
    change-log: classpath:db/changelog-master.xml

mybatis:
  type-aliases-package: com.inclination.scaffold.infrastraction.repository.po
  mapper-locations: classpath:mapper/*.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

app:
  id: scaffold
apollo:
  meta: http://127.0.0.1:8080
  bootstrap:
    enabled: true
    eagerLoad:
      enabled: true
    namespaces: application,TEST1.common

rest:
  http:
    timeout: 1500
    read:
      timeout: 5000
    connnection:
      request:
        timeout: 100

Scaffold:
  tool:
    project:
      git-url: http://localhost:3000/
      git-admin: root
      git-password: tianjingle
      jenkins-url: http://127.0.0.1:9001/
      jenkins-admin: admin
      jenkins-password: tianjingle
      monitor-view: monitor
  maven:
    env: dev
    script: mvn archetype:generate -DgroupId={0} -DartifactId={1} -Dversion=1.0.0-SNAPSHOT -Dpackage={2}  -DarchetypeGroupId=net.cnki -DarchetypeArtifactId=discuss-archetype -DarchetypeVersion=1.0.0-SNAPSHOT -B -DarchetypeCatalog=local -DinteractiveMode=false